### ISSUE TITLE
List contributions to your personal open-source projects

### ISSUE THREAD

**Issue by schollz** [jubalh/gontributions#14]
Could there be an option to list personal open-source projects ? The infrastructure you have here would make it pretty easy to do, but I want to know whether you think this is within the scope of this project. Namely it would be nice to have a contributions page like:

```
Contributions to other projects:

openSUSE 
openSUSE Linux distribution 
322 contributions 

...contributions to other projects..

My Projects (* = founded by me):

gontributions *
open source contributions lister
68 contributions 

...my own projects...
```

I think this would be easy to do. You could just clone repos as before, but you would count the number of commits by each person and determine 

1) If it is founded by you by looking at whether you made the first commit, and 
2) whether it is *your project* by seeing if the majority of contributions came from you. 

Then you could list it under `My Projects` if the majority was contributed by you and add a `*` if it is founded by you.

**Comment by jubalh** [comment]
Well there could also be projects that you created the first commit but arent your personal ones but a company project, or the project of a friend who wanted your help to get the project started.
Same applies for majority.

However we could create a flag into the config files like this:
```
...h
    "Projects": [
        {
            "Name": "nudoku",
            "Description": "Ncurses sudoku game",
            "URL": "",
            "Gitrepos": [
                "https://github.com/jubalh/nudoku"
            ],
            "Hgrepos": null,
            "MediaWikis": null,
            "Obs": null,
            "Owner": true,h
        },
...

Then the user can choose to highlight those in a special way by adjusting his template file.h
```

**Comment by jubalh** [comment]
@schollz I added a 'role' field. It can now be set to 'maintainer' or 'creator' or whatever one likes for one projects.
