### ISSUE TITLE
Don't make assumptions on template paths

### ISSUE THREAD

**Issue by fbsb** [jubalh/gontributions#17]
Right now when I provide a template via the `--template` flag the binary assumes the template are located inside templates directory.

```
$ gontributions --template fancy-template.html --config example.json --output index.html
Asset templates/fancy-template.html not found
```

I expect the `--template` flag to allow for full/relative paths

**Comment by jubalh** [comment]
Yeah like I said I have to work on that code, its right from the start when I experimented with things.
It only looks for the assets in that directory. The ones created by me and shipped as examples, built in the application.
The error message is thus misleading as it does not really look in that directory but in the assets under that "directory".
