### ISSUE TITLE
I am unable to use templates not bundled with the binary

### ISSUE THREAD

**Issue by fbsb** [jubalh/gontributions#18]
When providing the a template called `default.html` to the `--template` flag the output is generated with no errors.

```
$ gontributions --template default.html --config example.json --output index.html
* Working on https://github.com/jubalh/nudoku
Already up-to-date.
==> jubalh@openmailbox.org: 30 commits
==> g.bluehut@gmail.com: 53 commits
* Working on https://github.com/boothj5/profanity
Already up-to-date.
==> jubalh@openmailbox.org: 9 commits
* Working on https://github.com/funtoo/ego
Already up-to-date.
==> g.bluehut@gmail.com: 5 commits
* Working on https://github.com/funtoo/metro
Already up-to-date.
==> g.bluehut@gmail.com: 1 commits
* Working on MediaWiki http://funtoo.org as jubalh
==> 93 edits

Report saved in: index.html
```

Whereas when using a template called fancy.html the binary can't find any template.

```
$ gontributions --template fancy.html --config example.json --output index.html
Asset templates/fancy.html not found
```

Moving the `fancy.html` template to a directory called `templates` does not help.

**Comment by jubalh** [comment]
Yep currently `--template` picks only built-in templates.
`GONTRIB_TEMPLATES_PTH` needs to be set to check in directories for user made templates.
See here: https://github.com/jubalh/gontributions/blob/master/USAGE.md

**Comment by jubalh** [comment]
https://github.com/jubalh/gontributions/blob/master/HACKING.md describes on how to create new built-in templates.
But I think the two basic ones are enough. And once a new nice looking template is finished we will create a new repo and collect them all there.

**Comment by fbsb** [comment]
Is there any plan to support user defined templates in the near future?
